### ISSUE TITLE
Check newsletter subscription

### ISSUE THREAD

**Issue by MDCore** [CTFEDs/RapeCrisisCapeTownTrust#21]
It appears to use newsletter tycoon. We need the mailchimp details from Sarah

**Comment by MDCore** [comment]
@SteveBarnett to switch it over to MailChimp now he has the deets.

**Comment by sarah** [comment]
You tagged the wrong sarah and have now given me access to your repo. Might wanna change that...

**Comment by MDCore** [comment]
Hi @sarah. I realised as soon as it hyperlinked your name that I'd tagged a stranger! Sorry about that, and apologies for the spamming. I'll be more careful with my @ symbol in the future :)

**Comment by sarah** [comment]
No worries :) it'd be nice if GitHub did a check: I have a common name ,
this isn't the first time ;)

Sent from my iPhone

On May 10, 2014, at 11:13 AM, Gavin van Lelyveld notifications@github.com
wrote:

Hi @sarah https://github.com/sarah. I realised as soon as it hyperlinked
your name that I'd tagged a stranger! Sorry about that, and apologies for
the spamming. I'll be more careful with my @ symbol in the future :)

—
Reply to this email directly or view it on
GitHubhttps://github.com/CTFEDs/RapeCrisisCapeTownTrust/issues/21#issuecomment-42746181
.

**Comment by SteveBarnett** [comment]
Swtiched to MailChimp, deleted newsletter tycoon plugin, emailed Sara subscriber list form that.
