### ISSUE TITLE
Insert full addresses and maps of all offices

### ISSUE THREAD

**Issue by MDCore** [CTFEDs/RapeCrisisCapeTownTrust#22]
We need the addresses.

**Comment by MDCore** [comment]
**Athlone**: 335a Klipfontein Road, Gatesville
**Observatory**: 23 Trill Road, Observatory
**Khayelitsha**: 89 Msobomvu Drive, Ilitha Park, Khayelitsha

**Comment by SteveBarnett** [comment]
Added to production: http://rapecrisis.org.za/contact/
