### ISSUE TITLE
Convert telephone numbers to HTML5 format

### ISSUE THREAD

**Issue by MDCore** [CTFEDs/RapeCrisisCapeTownTrust#26]
To make them clickable on mobile devices.

**Comment by Investhost** [comment]
Here are the html5 tel. numbers

Contact our offices:
Observatory: <a href="tel:+27214471467">021 447 1467</a>
Athlone: <a href="tel:+27216841180">021 684 1180</a>
Khayelitsha: <a href="tel:+27213619228">021 361 9228</a>

Counselling lines:
Observatory: <a href="tel:+27214479762">021 447 9762</a>
Athlone: <a href="tel:+27216339229">021 633 9229</a>
Khayelitsha: <a href="tel:+27213619085">021 361 9085</a>

**Comment by SteveBarnett** [comment]
Updated production via WordPress: http://rapecrisis.org.za/contact/
