### ISSUE TITLE
Navigation 

### ISSUE THREAD

**Issue by mrkiffie** [CTFEDs/RapeCrisisCapeTownTrust#32]
1. Going for menu in the footer as the most basic solution
2. Progressively enhanced to an off-canvas nav 
   - which will utilize css transform to manipulate it 
   - media queries to further enhance the menu layout on larger screens 

Which would be better for wider screens?
- a horizontal menu with dropdown (js powered for touch devices?)
- a layout similar to a sitemap
- same off-canvas menu as the other

**Comment by SteveBarnett** [comment]
@mrkiffie We want to keep the big screen version looking similar to the current site, so a horizontal with dropdowns, I think.
