### ISSUE TITLE
Content: Staff update

### ISSUE THREAD

**Issue by MDCore** [CTFEDs/RapeCrisisCapeTownTrust#4]

**Comment by SteveBarnett** [comment]
Sarah says:

> Also can you add the attached pic under http://rapecrisis.org.za/about-rape-crisis/staff/  in place of Helette Gelderbloem, and put my name Sarah Strydom,
> And delete the pic for Liezel Van Schalkway and change text to Estelle Carolissen, job title Court Support Coordinator…

**Comment by SteveBarnett** [comment]
Need a pic of Estelle Carolissen, pinged Sarah requesting it.
